title: VEUCTOR
description: Training, Selecting, and Aligning Word Embeddings from European Online Job Advertisements
url: https://crisp-unimib.github.io
baseurl: /veuctor

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

aux_links:
  "GitHub repository":
    - "https://github.com/Crisp-Unimib/veuctor"

# opzionale: mostra un link "Edit this page"
gh_edit_link: true
gh_edit_repository: "https://github.com/Crisp-Unimib/veuctor"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

